apiVersion: v2
name: kafka-art
description: Kafka chart for ArgoCD
type: application
version: 0.1.0
dependencies:
  - name: kafka
    condition: kafka.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 32.4.3