grafana:
  revisionHistoryLimit: 3

  testFramework:
    enabled: false

  ingress:
    enabled: true
    ingressClassName: traefik   # или system-ingress, если такой IngressClass действительно есть
    annotations:
      cert-manager.io/cluster-issuer: dev-ca-issuer
    hosts:
      - grafana.maxim.local
    path: /
    pathType: Prefix
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.maxim.local

  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

  persistence:
    enabled: true
    type: pvc
    storageClassName: nfs-client
    accessModes:
      - ReadWriteOnce
    size: 2Gi

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Victoria
          type: prometheus
          url: http://victoriametrics-victoria-metrics-single-server:8428
          access: proxy
          isDefault: true
