---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-rules-config-cpu
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: victoria-metrics-alert
    app.kubernetes.io/version: v1.148.0
data:
  alert-rules.yaml: |
    groups:
      - name: resources-cpu
        rules:
          - alert: NodeCpuUsage
            annotations:
              description: "Средняя загрузка процессора по ядрам на (instance {{ $labels.lhostname
            }}) превышает допустимые значения. \n\n Текущее значение: {{ humanize $value
            }}%."
              summary: "Дополнительная информация: \n "
            expr: 100 - avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) without (cpu)
              * 100 > 85
            for: 5m
            labels:
              severity: warning